# Generated by Django 5.0.7 on 2024-07-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviessearched',
            name='count',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
