# Generated by Django 5.0.7 on 2024-07-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_moviessearched_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviessearched',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
